// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt7-Ds3pahI8uhrp1aKKO07a3KV0GjLZc',
    appId: '1:945390667505:web:55b205fc03968f74bf8b50',
    messagingSenderId: '945390667505',
    projectId: 'college-meeting-room',
    authDomain: 'college-meeting-room.firebaseapp.com',
    storageBucket: 'college-meeting-room.firebasestorage.app',
    measurementId: 'G-B3LB4KC0VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY0aHvtsFDxi7A_PBSFkZLOI0niNC0cCo',
    appId: '1:945390667505:android:a1f65f5b94b07017bf8b50',
    messagingSenderId: '945390667505',
    projectId: 'college-meeting-room',
    storageBucket: 'college-meeting-room.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz-KpM8JeDTCVV1hCADDgQCHFQGHKzOeM',
    appId: '1:945390667505:ios:454ebbf2a8f071dabf8b50',
    messagingSenderId: '945390667505',
    projectId: 'college-meeting-room',
    storageBucket: 'college-meeting-room.firebasestorage.app',
    iosBundleId: 'com.example.collegeMeetingRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz-KpM8JeDTCVV1hCADDgQCHFQGHKzOeM',
    appId: '1:945390667505:ios:454ebbf2a8f071dabf8b50',
    messagingSenderId: '945390667505',
    projectId: 'college-meeting-room',
    storageBucket: 'college-meeting-room.firebasestorage.app',
    iosBundleId: 'com.example.collegeMeetingRoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt7-Ds3pahI8uhrp1aKKO07a3KV0GjLZc',
    appId: '1:945390667505:web:457c190fe3735d5bbf8b50',
    messagingSenderId: '945390667505',
    projectId: 'college-meeting-room',
    authDomain: 'college-meeting-room.firebaseapp.com',
    storageBucket: 'college-meeting-room.firebasestorage.app',
    measurementId: 'G-GLYZ551E07',
  );
}
